#Perform the RHEL 8 to RHEL 9 upgrade - using roles
- hosts: rhel
  vars:
    current_version: 8.7
    target_version: 9.0
  tasks:
    - name: Prepare RHEL for upgrade
      include_role:
        name: prepare-rhel-upgrade
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"
    - name: Changes for our demo env
      include_role:
        name: demo-prepare-rhel-upgrade
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"

    - name: Enable and start podman socket service for docker-compose compataiblity
      become: true
      ansible.builtin.systemd:
        name: podman.socket
        state: started

    - name: Stop appplication during update
      become: true
      community.docker.docker_compose:
        project_src: /root/demo
        state: absent
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"

    - name: Preform RHEL upgrade
      include_role:
        name: rhel-upgrade
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"
  
    - name: Enable and start podman socket service for docker-compose compataiblity
      become: true
      ansible.builtin.systemd:
        name: podman.socket
        state: started

    - name: Start appplication after update
      become: true
      ansible.builtin.shell:
        cmd: /root/.local/bin/docker-compose up -d
        chdir: /root/demo
      when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"
